web/router.ex
defmodule Cataloger.Router do
  use Cataloger.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Cataloger do
    pipe_through :browser

    get "/", CatalogController, :index
    resources "/catalogs", CatalogController
    get "/catalogs/export/:id", CatalogController, :export
    resources "/sections", SectionController
    get "/preferences", PreferenceController, :index
    get "/preferences/edit", PreferenceController, :edit
    post "/preferences", PreferenceController, :update
    resources "/items", ItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Cataloger do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Cataloger.LayoutView do
  use Cataloger.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cataloger - <%= assigns[:page_title] || "Home" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="<%= preference_path(@conn, :index) %>">Preferences</a></li>
            <li><a href="<%= static_path(@conn, "/") %>">Home</a></li>
          </ul>
        </nav>
        <span class="title">
          <%= if assigns[:page_title], do: assigns[:page_title], else: "Cataloger" %>
        </span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>