web/router.ex
defmodule Cataloger.Router do
  use Cataloger.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Cataloger do
    pipe_through :browser

    get "/", CatalogController, :index
    resources "/catalogs", CatalogController
    get "/catalogs/export/:id", CatalogController, :export
    resources "/sections", SectionController
    get "/preferences", PreferenceController, :index
    get "/preferences/edit", PreferenceController, :edit
    post "/preferences", PreferenceController, :update
    resources "/items", ItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Cataloger do
  #   pipe_through :api
  # end
end

web/models/section.ex
defmodule Cataloger.Section do
  use Cataloger.Web, :model

  schema "sections" do
    field :name, :string
    field :cover_image_path, :string
    field :description, :string
    belongs_to :catalog, Cataloger.Catalog

    timestamps
  end

  @required_fields ~w(name catalog_id)
  @optional_fields ~w(cover_image_path description)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/section_controller.ex
defmodule Cataloger.SectionController do
  use Cataloger.Web, :controller

  alias Cataloger.Section

  plug :scrub_params, "section" when action in [:create, :update]

  def index(conn, _params) do
    sections = Repo.all(Section)
    render(conn, "index.html", sections: sections)
  end

  def new(conn, params) do
    changeset = Section.changeset(%Section{}, params)
    render(conn, "new.html",
           changeset: changeset,
           catalog_id: params["catalog_id"])
  end

  def create(conn, %{"section" => section_params}) do
    changeset = Section.changeset(%Section{}, section_params)

    case Repo.insert(changeset) do
      {:ok, _section} ->
        conn
        |> put_flash(:info, "Section created successfully.")
        |> redirect(to: catalog_path(conn, :show, section_params["catalog_id"]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    section = Section |> Repo.get!(id) |> Repo.preload([:catalog, :items])
    render(conn, "show.html", section: section, page_title: "'#{section.name}' Section")
  end

  def edit(conn, %{"id" => id}) do
    section = Repo.get!(Section, id)
    changeset = Section.changeset(section)
    render(conn, "edit.html", section: section, changeset: changeset)
  end

  def update(conn, %{"id" => id, "section" => section_params}) do
    extra_cover_image =
      case section_params["cover_image"] do
        nil ->
          %{}
        _ ->
          temp_path = section_params["cover_image"].path

          original_filename = section_params["cover_image"].filename
          original_extension = String.replace(original_filename, ~r/.*\./, "")
          base_image_path = Application.get_env(:cataloger, :store)[:images]
          final_path = Path.join(base_image_path,
                                 "section-" <> id <> "." <> original_extension)

          case File.rename(temp_path, final_path) do
            :ok ->
              %{"cover_image_path" => Path.basename(final_path)}
            {:error, _reason} ->
              %{}
          end
      end

    section = Repo.get!(Section, id)
    changeset = Section.changeset(section,
                                  Map.merge(section_params, extra_cover_image))

    case Repo.update(changeset) do
      {:ok, section} ->
        conn
        |> put_flash(:info, "Section updated successfully.")
        |> redirect(to: section_path(conn, :show, section))
      {:error, changeset} ->
        render(conn, "edit.html", section: section, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    section = Repo.get!(Section, id)
    catalog_id = section.catalog_id

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(section)

    conn
    |> put_flash(:info, "Section deleted successfully.")
    |> redirect(to: catalog_path(conn, :show, catalog_id))
  end
end

web/views/section_view.ex
defmodule Cataloger.SectionView do
  use Cataloger.Web, :view
end

web/templates/section/edit.html.eex
<h2>Edit section</h2>

<%= render "form.html", changeset: @changeset,
                        action: section_path(@conn, :update, @section) %>

<%= link "Back", to: section_path(@conn, :show, @section.id) %>

web/templates/section/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :catalog_id, class: "form-control" %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :cover_image, class: "control-label" %>
    <%= file_input f, :cover_image, class: "form-control" %>
    <%= error_tag f, :cover_image %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/section/index.html.eex
<h2>Listing sections</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Cover image path</th>
      <th>Catalog</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for section <- @sections do %>
    <tr>
      <td><%= section.name %></td>
      <td><%= section.cover_image_path %></td>
      <td><%= section.catalog_id %></td>

      <td class="text-right">
        <%= link "Show", to: section_path(@conn, :show, section), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: section_path(@conn, :edit, section), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: section_path(@conn, :delete, section), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New section", to: section_path(@conn, :new) %>

web/templates/section/new.html.eex
<h2>New section</h2>

<%= render "form.html", changeset: @changeset,
                        action: section_path(@conn, :create) %>

<%= link "Back", to: catalog_path(@conn, :show, @catalog_id) %>

web/templates/section/show.html.eex
<div class="big-description"><%= @section.description %></div>

<%= if @section.items == [] do %>
<h2>No items in this section</h2>
<% else %>

<ul class="entity-list">
  <%= for item <- @section.items do %>
    <li>
      <a href="<%= item_path(@conn, :edit, item.id) %>">
        <div class="frame">
          <img src="<%= static_path(@conn, "/images/" <> (item.cover_image_path || "default-item.png")) %>" />
        </div>
        <div class="caption">
          <%= item.name %>
          <div class="tags" title="<%= item.tags %>">
            <%= item.tags %>
          </div>
        </div>
      </a>
    </li>
  <% end %>
</ul>
<% end %>

<%= link "New item",
    to: item_path(@conn,
                  :new,
                  item: %{section_id: @section.id}) %>
/
<%= link "Edit", to: section_path(@conn, :edit, @section) %>
/
<%= link "Delete", to: section_path(@conn, :delete, @section), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
/
<%= link "Back", to: catalog_path(@conn, :show, @section.catalog) %>