web/router.ex
defmodule Cataloger.Router do
  use Cataloger.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Cataloger do
    pipe_through :browser

    get "/", CatalogController, :index
    resources "/catalogs", CatalogController
    get "/catalogs/export/:id", CatalogController, :export
    resources "/sections", SectionController
    get "/preferences", PreferenceController, :index
    get "/preferences/edit", PreferenceController, :edit
    post "/preferences", PreferenceController, :update
    resources "/items", ItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Cataloger do
  #   pipe_through :api
  # end
end

web/models/catalog.ex
defmodule Cataloger.Catalog do
  use Cataloger.Web, :model
  alias Cataloger.Repo

  schema "catalogs" do
    field :name, :string
    has_many :sections, Cataloger.Section

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:name, max: 120)
  end

  def all_image_paths(catalog) do
    base_image_path = Application.get_env(:cataloger, :store)[:images]
    catalog = Repo.preload(catalog, :sections)

    Enum.reduce(catalog.sections, [], fn(section, images) ->
      section = Repo.preload(section, :items)

      item_images = Enum.reduce(section.items, [], fn(item, images) ->
        if item.cover_image_path do
          [Path.join(base_image_path, item.cover_image_path) | images]
        else
          images
        end
      end)

      if section.cover_image_path do
        section_image = Path.join(base_image_path, section.cover_image_path)
        images ++ [section_image] ++ item_images
      else
        images ++ item_images
      end
    end)
  end
end

web/controllers/catalog_controller.ex
defmodule Cataloger.CatalogController do
  use Cataloger.Web, :controller

  alias Cataloger.Catalog

  plug :scrub_params, "catalog" when action in [:create, :update]

  def index(conn, _params) do
    catalogs = Repo.all(Catalog)
    render(conn, "index.html", catalogs: catalogs)
  end

  def new(conn, _params) do
    changeset = Catalog.changeset(%Catalog{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"catalog" => catalog_params}) do
    changeset = Catalog.changeset(%Catalog{}, catalog_params)

    case Repo.insert(changeset) do
      {:ok, _catalog} ->
        conn
        |> put_flash(:info, "Catalog created successfully.")
        |> redirect(to: catalog_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    catalog = Catalog |> Repo.get!(id) |> Repo.preload([:sections])
    render(conn, "show.html", catalog: catalog, page_title: catalog.name)
  end

  def edit(conn, %{"id" => id}) do
    catalog = Repo.get!(Catalog, id)
    changeset = Catalog.changeset(catalog)
    render(conn, "edit.html", catalog: catalog, changeset: changeset)
  end

  def update(conn, %{"id" => id, "catalog" => catalog_params}) do
    catalog = Repo.get!(Catalog, id)
    changeset = Catalog.changeset(catalog, catalog_params)

    case Repo.update(changeset) do
      {:ok, catalog} ->
        conn
        |> put_flash(:info, "Catalog updated successfully.")
        |> redirect(to: catalog_path(conn, :show, catalog))
      {:error, changeset} ->
        render(conn, "edit.html", catalog: catalog, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    catalog = Repo.get!(Catalog, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(catalog)

    conn
    |> put_flash(:info, "Catalog deleted successfully.")
    |> redirect(to: catalog_path(conn, :index))
  end

  def export(conn, %{"id" => id}) do
    catalog = Repo.get!(Catalog, id)
    base_export_dir = Application.get_env(:cataloger, :export_dir)
    catalog_export_dir = Path.join(base_export_dir, id)

    # Delete the export directory
    File.rm_rf! catalog_export_dir

    render(conn, "export.html",
           catalog: catalog,
           exported_dir: catalog_export_dir)
  end
end

web/views/catalog_view.ex
defmodule Cataloger.CatalogView do
  use Cataloger.Web, :view
end

web/templates/catalog/edit.html.eex
<h2>Edit catalog</h2>

<%= render "form.html", changeset: @changeset,
                        action: catalog_path(@conn, :update, @catalog) %>

<%= link "Back", to: catalog_path(@conn, :show, @catalog.id) %>

web/templates/catalog/error.html.eex
<h2>Error exporting catalog</h2>

<p><%= @message %></p>

Exception was: <%= @error %>.

web/templates/catalog/export.html.eex
<p id="progress-info"></p>

<%= link "Back", to: catalog_path(@conn, :show, @catalog.id) %>

<script>
  window.addEventListener("load", function() {
      var catalogExporter = require("web/static/js/catalog-exporter").default;
      var progressInfoEl = document.getElementById("progress-info");
      catalogExporter(<%= @catalog.id %>, progressInfoEl);
  }, false);
</script>

web/templates/catalog/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/catalog/index.html.eex
<h2>Available catalogs</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for catalog <- @catalogs do %>
    <tr>
      <td><%= catalog.name %></td>

      <td class="text-right">
        <%= link "Show", to: catalog_path(@conn, :show, catalog), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: catalog_path(@conn, :edit, catalog), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: catalog_path(@conn, :delete, catalog), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New catalog", to: catalog_path(@conn, :new) %>

<footer>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> and <a href="http://www.flaticon.com/authors/lyolya" title="Lyolya">Lyolya</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>.</footer>

web/templates/catalog/new.html.eex
<h2>New catalog</h2>

<%= render "form.html", changeset: @changeset,
                        action: catalog_path(@conn, :create) %>

<%= link "Back", to: catalog_path(@conn, :index) %>

web/templates/catalog/show.html.eex
<ul class="entity-list section-list">
  <%= for section <- @catalog.sections do %>
    <li>
      <a href="<%= section_path(@conn, :show, section) %>" title="<%= section.description %>">
        <div class="frame">
          <img src="<%= static_path(@conn, "/images/" <> (section.cover_image_path || "default-section.png")) %>" />
        </div>
        <div class="caption">
          <%= section.name %>
        </div>
      </a>
    </li>
  <% end %>
</ul>

<%= link "New section",
    to: section_path(@conn,
                     :new,
                     catalog_id: @catalog.id) %>
/
<%= link "Edit", to: catalog_path(@conn, :edit, @catalog) %>
/
<%= link "Export", to: catalog_path(@conn, :export, @catalog.id) %>
/
<%= link "Back", to: catalog_path(@conn, :index) %>